FROM python:3.12-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

ADD . /app
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy UV_PYTHON_CACHE_DIR=/root/.cache/uv/python


RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync

CMD ["bash", "-c", "uv run app/manage.py migrate --no-input && uv run app/manage.py runserver 0.0.0.0:8080"]
